apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sample-deployment
  namespace: development
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8sample
        visualize: "true"
    spec:
      containers:
      - name: k8sample-pod
        image: estebanmate/emtp/k8sample:1.0
        ports:
        - containerPort: 8090       
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 1        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: k8sample-service
  namespace: development
spec:
  selector:
    app: k8sample
  ports:
  - name: http
    protocol: TCP
    port: 8090
    targetPort: 80890
  type: ClusterIP
